version: '3.8'

services:
  wasm-compiler:
    build: .
    container_name: wasm-compiler
    restart: unless-stopped
    network_mode: "service:tailscale"
    depends_on:
      - tailscale
    privileged: true
    user: podman
    security_opt:
      - "label=disable"
      - "seccomp=unconfined"
    devices:
      - /dev/fuse:/dev/fuse
    env_file:
      - .env

  tailscale:
    image: tailscale/tailscale:latest
    hostname: wasm-compiler
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped

volumes:
  tailscale-state:
