[package]
name = "pyroduct-module"
version = "0.1.0"
edition = "2024"

# Commented out due to fetch
[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.4.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
regex = "1.11.1"